### PR TITLE
Update 1.18.2 KillAura

### PR DESCRIPTION
**Pull request by ghost**
Decided to update the KillAura for myself, and deciding to push this out, hopefully this gets accepted for everyone else.

Not very experienced with Java, but I haven't had any issues with these changes in my games.

### CODE REVIEW

**Comment by ghost** [comment]
All I did was try to incorporate the kill aura from 1.21 to allow for the attack speed to be based off the weapon you are using. Then I just updated the GUI and incorporated those changes as well.

**Comment by Zergatul** [comment]
From what I see few UI options will not work. Like attackAll or autoRotate. Updated code doesn't do anything with them.
Could you remove or hide them from the UI to not confuse people.

**Comment by ghost** [comment]
> From what I see few UI options will not work. Like attackAll or autoRotate. Updated code doesn't do anything with them. Could you remove or hide them from the UI to not confuse people.

Removed!

**Comment by ghost** [comment]
Sorry, I had one more change to remove the clamping I added. Should I open a new PR?

```
    public void validate() {
        maxRange = MathUtils.clamp(maxRange, 1, 100);
        attackTickInterval = MathUtils.clamp(attackTickInterval, 1, 100);
        // Removed clamping for extraTicks, delete this line
        if (maxHorizontalAngle != null) {
            maxHorizontalAngle = MathUtils.clamp(maxHorizontalAngle, 1, 180);
        }
        if (maxVerticalAngle != null) {
            maxVerticalAngle = MathUtils.clamp(maxVerticalAngle, 1, 180);
        }

        priorities = priorities.removeIf(Objects::isNull);
        customEntries = customEntries.removeIf(Objects::isNull);
    }
```

**Comment by Zergatul** [comment]
What is wrong with clamping extraTicks?

**Comment by ghost** [comment]
Nothing really, it was just set to +/- 10. Not a huge deal, but someone may want to have 100 extra ticks.

**Comment by Zergatul** [comment]
Then it is better to clamp lets say from -10 to 1000

**Comment by Zergatul** [comment]
You can create new PR for this. No need to hurry, if you have something else on your mind add it too

**Comment by ghost** [comment]
> You can create new PR for this. No need to hurry, if you have something else on your mind add it too

Okay, thanks. I'll look around and see if there's anything else I can add.

**Pull request merged**
